### ISSUE TITLE
请问docker里面python对应的依赖要怎么装呢

### ISSUE THREAD

**Issue by dudylan** [petrvlcek/mitmproxy-docker#2]

**Comment by dudylan** [comment]
脚本对应的依赖

**Comment by dudylan** [comment]
How to install dependencies corresponding to Script

**Comment by dudylan** [comment]
Thank you

**Comment by petrvlcek** [comment]
The only prerequisite is Docker on your machine. Could you be more specific?

**Comment by dudylan** [comment]
For example, I use your project to execute a script. The script needs to use the aiohttp module. What should I do

**Comment by dudylan** [comment]
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/34180156/174478892-d276719f-5de3-4096-930d-b222fcda01b7.png">

**Comment by petrvlcek** [comment]
If you need to use any extra dependencies I think you need to create a new Dockerfile extending `mitmproxy/mitmproxy`, and build your Python project within this Dockerfile including any dependencies.

**Comment by dudylan** [comment]
OK， Thank you
